### ISSUE TITLE
Better formatting of graph for histogram.py

### ISSUE THREAD

**Issue by bkowshik** [bitly/data_hacks#31]
There needs to be **better formatting** to take care of;
* Minus symbol for negative numbers.
* Number of digits in the number.

Below is a screenshot highlighting the above.

![formatting_in_histogram](https://cloud.githubusercontent.com/assets/2899501/12258072/c2e81a18-b931-11e5-89ca-607533cecc29.png)

**Comment by havanagrawal** [comment]
You could use the --bucket-format option to add sufficient padding yourself. It worked for me.
![capture](https://cloud.githubusercontent.com/assets/7271807/14714690/94c15f16-0803-11e6-9b26-0fef9cf2279c.PNG)

**Comment by bkowshik** [comment]
`--bucket-format` works for me too. Thank you @havanagrawal 

Closing this ticket.
